### ISSUE TITLE
Querying a doc should allow filtering/sorting on Child Table

### ISSUE THREAD

**Issue by nabilshuja** [leam-tech/frappe_graphql#37]
Given this ability, it would allow added bonus of requesting only what is desired. And this could be the same as current use of generating `[DBFilterInput]` for filters, as well as `SortingInput` for each field in the child table. 

```graphql
User(name: "johndoe@gmail.com"){
    roles(filter: [
        {
            fieldname: "role"
            operator: LIKE
            value: "Manager"
        }
    ]){
        name
    }
}
```
In my use case I'd prefer only getting single row in the child table hence filtering by `name`.

**Comment by fahimalizain** [comment]
@nabilshuja
I believe introducing this generically will introduce unwanted overheads. We could always customize the default behavior where required. Closing this as per the discussion we had earlier.
