### ISSUE TITLE
LIKE operator of filter not working as intended

### ISSUE THREAD

**Issue by nabilshuja** [leam-tech/frappe_graphql#45]
When doing a query on a list, the operator doesn't seem to be working as intended, its working as more of a EQ operator.
for example;

<table>
<tr>
	<td>
	<img width="1160" alt="image" src="https://user-images.githubusercontent.com/25796380/133963883-549769d1-f57e-4745-82f9-e4197ca0a3f7.png">
	<td>
		
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/25796380/133963915-4e1a4c49-3135-4520-8396-efc4384dba04.png">

<tr>
</table>

**Comment by e-lobo** [comment]
@nabilshuja using `wildcard("%")` is a choice given to the user and it works fine. @fahimalizain @assemmarwan please confirm and close issue ? 
![image](https://user-images.githubusercontent.com/41537985/146174345-eb956284-5003-443e-a4a1-5b18c7ddf7ec.png)

**Comment by nabilshuja** [comment]
fair enough, will close.
