### ISSUE TITLE
Improve error message "Please fix your HEAD on select field"

### ISSUE THREAD

**Issue by carstenblt** [leam-tech/frappe_graphql#49]
First, this is a dream come true. Thank you very much for this work! Is this package considered production ready?

When creating the sdl I receive the following exception:
`frappe.exceptions.ValidationError: Please fix your HEAD on select field: 96880af9cf`

I guess I understand the problem after reading the code. However it would help if the description was better. Also, I have no idea how to find this field to fix it. Is there any way to search for this hash?

**Comment by e-lobo** [comment]
@carstenblt 
[Here](https://github.com/leam-tech/frappe_graphql/blob/759ee22bb0b23240a02f9eb2036b8fac8eb9d850/frappe_graphql/utils/generate_sdl/doctype.py#L212)'s error being thrown 😄 .. make sure your select field has no empty field maybe or you can skip generation of select fields graphql enums with the `--disable-enum-select-fields` flag on `generate_sdl`

**Comment by carstenblt** [comment]
Thanks for the quick response! I quickly added some debug code to find them - however with ERPNext there are a lot of those on built-in doctypes! I guess you could skip the empty values however - frappe won't let you save them anyways and you could just not include them in the enums?

**Comment by Abadulrehman** [comment]
@carstenblt 
I think that is why the `--disable-enum-select-fields` exists. 😅 You could run two different commands for generating; when generating them for built-in doctypes, you could use this flag?

**Comment by carstenblt** [comment]
Seems reasonable. Thank you!
