### ISSUE TITLE
generate-sdl command support for full ERPNext Doctype suite

### ISSUE THREAD

**Issue by fahimalizain** [leam-tech/frappe_graphql#51]
- Some doctypes conflict with gql-reserved types, eg. Subscription
- Pluralization of some doctypes are broken
- Remove validation on Select-DocFields that are reqd and has an empty option

**Comment by carstenblt** [comment]
```
frappe_graphql.utils.exceptions.GraphQLFileSyntaxError: Could not load ./mysite/doctype_sdls/c_form.graphql:
Syntax Error: Invalid number, expected digit but got: 'F'.
GraphQL request:1:8
1 | type C-Form implements BaseDocType {
  |        ^
  |   doctype: String"
```
I guess that one is ERPNext specific too?

**Comment by fahimalizain** [comment]
True 👍🏼 
For now, instead of making SDLs for all ERPNext doctypes, you could try making only for those doctypes that do not make any said issue

```
$ bench graphql generate_sdl -dt "Sales Invoice" -dt Item -dt <....>
```

**Comment by carstenblt** [comment]
Awesome. It's gonna be a loooong list because of all the connected types. But I'll try.

**Comment by e-lobo** [comment]
> Awesome. It's gonna be a loooong list because of all the connected types. But I'll try.

`bench graphql generate_sdl ` also has generate by module support `--module`

**Comment by carstenblt** [comment]
Working in reverse worked better, I removed all C-Form and Content (?) types but now I'm left with infinite
`Field 'DocTypeAction.modified_by' can only be defined once.`
on DynamicLink, DocTypeLink, Query, etc.

**Comment by carstenblt** [comment]
Got it running... Doctype* and Query types have to be removed as well.

```
  SalesOrder(name: "SAL-ORD-2021-01032") {
    name
  }
```

takes 25 seconds to execute however.

**Comment by e-lobo** [comment]
> Got it running... Doctype* and Query types have to be removed as well.
> 
> ```
>   SalesOrder(name: "SAL-ORD-2021-01032") {
>     name
>   }
> ```
> 
> takes 25 seconds to execute however.

consecutively? i believe only on first ever request its slow.. then schema is cached and it should be fast.. we are working on the initial request response time 😄

**Comment by carstenblt** [comment]
Uh, it was the load balancer - had to cache it on all servers. I'll explore it more next week. Thank you for your patience!
