### ISSUE TITLE
Queries return translated values

### ISSUE THREAD

**Issue by carstenblt** [leam-tech/frappe_graphql#52]
Running a query returns translated values (e.g. German "Entwurf" instead of "Draft" for a "status" field in ERPNext).

For an API, the untranslated values should be returned.

**Comment by e-lobo** [comment]
@carstenblt try sending the `Accept-Language` header in your request. Translations are returned for every field [here](https://github.com/leam-tech/frappe_graphql/blob/2cbdef588f3cf47823a94eea80afbd4aa3955a87/frappe_graphql/utils/resolver/document_resolver.py#L52) based on frappe language translation [resolution](https://frappeframework.com/docs/user/en/python-api/language).

**Comment by carstenblt** [comment]
Works, thank you!
