### ISSUE TITLE
Generate the sdls throw's AttributeError: 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by afalfallaj** [leam-tech/frappe_graphql#79]
Once I Generate the sdls. I get AttributeError: 'NoneType' object has no attribute 'values' error.

https://github.com/leam-tech/frappe_graphql/blob/3fb5f9eeb9c79c60c1feb93956d95fbfa5a54482/frappe_graphql/utils/generate_sdl/doctype.py#L262

seems  generated_enums in line 262 reach empty.

I have added hasattr before and I don't get this error anymore. I don't why I get this error but I am using frappe & erpnext v13.5.2

```
if hasattr(generated_enums,'values'):
        if name in generated_enums.values():
            name = remove_reserved_characters(
                f"{doctype}{(docfield.fieldname).title()}SelectOptions"
                .replace(" ", ""))
```

**Comment by e-lobo** [comment]
feel free to make a pr @afalfallaj =)

**Comment by afalfallaj** [comment]
#80

**Comment by e-lobo** [comment]
https://github.com/leam-tech/frappe_graphql/pull/80 Merged
